apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "rabbitmq-data-claim"
spec:
#  storageClassName: "local"
#  volumeName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
