version: '3.8'

services:
    app:
        ports:
            - 'CUSTOM_PORT:8000'
        volumes:
            - .:/workspace
            - /workspace/node_modules
            - /workspace/.parcel-cache
            - /workspace/__pycache__
    db:
        ports:
            - '3306'