version: '3.8'

services:
    app:
        environment:
            EDITOR_VSCODE: 1
        volumes:
            - .:/workspace
            - /workspace/node_modules
        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        network_mode: service:db
