apiVersion: v1
kind: Service
metadata:
  name: {{include "datatracker.fullname" .}}
  labels: {{- include "datatracker.commonLabels" . | nindent 4 }}
  {{- with .Values.datatracker.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.datatracker.service.type}}
  ports:
    - port: {{ default "80" .Values.datatracker.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "datatracker.selectorLabels" . | nindent 4}}
    app.kubernetes.io/name: {{ .Values.datatracker.name }}
