apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels: {{- include "datatracker.commonLabels" . | nindent 4 }}
  {{- with .Values.memcached.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.memcached.service.type}}
  ports:
    - port: {{ default "11211" .Values.memcached.service.port}}
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector: 
    {{- include "datatracker.selectorLabels" . | nindent 4}}
    app.kubernetes.io/name: {{ .Values.memcached.name }}
