name: Build Celery Worker Docker Image

on:
  push:
    branches:
      - 'main'
      - 'jennifer/celery'
    paths:
      - 'requirements.txt'
      - 'dev/celery/Dockerfile'

  workflow_dispatch: 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datatracker-celery

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: latest
        registry: ${{ env.REGISTRY }}
        dockerfile: dev/celery/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
