name: Build Base Test Docker Image

on:
  push:
    branches:
      # TEMPORARY: Replace with main once bs5 is merged
      - 'feat/bs5'
    paths:
      - 'package.json'
      - 'requirements.txt'
      - 'dev/docker-test-base/Dockerfile'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datatracker-test-base

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: latest
        registry: ${{ env.REGISTRY }}
        dockerfile: dev/docker-test-base/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
