name: Run all tests

on:
  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/app.Dockerfile --tag dt-tests:$(date +%s)
    - name: Prepare the Docker container
      run: docker run dt-tests:$(date +%s)
