name: Run all tests

on:
  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start docker
      run: |
        docker-compose \
          --file docker-compose.yml \
          --file docker/docker-compose.extend.yml \
          up --detach
    - name: Run all tests
      run: |
        docker-compose exec app \
          /docker-init.sh /workspace/ietf/manage.py test \
            --settings=settings_local_sqlitetest \
            --failfast
    - name: Stop docker
      run: docker-compose stop
